import { suite } from 'uvu'
import * as assert from 'uvu/assert'

import { cwd } from 'process'
import { resolve, getFormat, getSource, transformSource } from '../src/index.js'
import { pathToFileURL } from 'url'
import path from 'path'

const backup = console.warn
const test = suite('loader')
const files = {
  svelte: 'file:///src/components/Counter.svelte',
  style: 'file:///static/styles/layout.css',
  svelteKitAlias: 'file:///$app/navigation',
}

test.before.each(() => {
  console.warn = () => {}
})

test.after.each(() => {
  console.warn = backup
})

test('resolve', async () => {
  const result = await resolve(files.svelte)
  assert.match(result.url, new RegExp(files.svelte))
})

test('resolve directory import', async () => {
  const sourceFile = `${cwd()}/examples/svelte/src/lib`
  const result = await resolve(sourceFile)

  assert.match(
    result.url,
    pathToFileURL(path.join(sourceFile, 'index.js')).href
  )
})

test('getFormat', async () => {
  const result = await getFormat(files.svelte)
  assert.is(result.format, 'module')
})

test('getSource on svelte-kit $app/navigation alias', async () => {
  const result = await getSource(files.svelteKitAlias)
  const source = result.source.toString()
  assert.match(source, 'export { goto }')
})

test('getSource on .css', async () => {
  const result = await getSource(files.style)
  assert.match(result.source, '')
})

test('transformSource on .svelte', async () => {
  const source = `
    <script>
      const hello = 1
    </script>
    <div>
      <span>{hello}</span>
    </div>
    <style>
      span { color: red }
    </style>
  `
  const result = await transformSource(source, { url: files.svelte })
  assert.match(result.source, new RegExp(files.svelte))
  assert.match(result.source, /generated by Svelte/)
})

test('transformSource on preprocessed .svelte', async () => {
  const source = `
    <script>
      const hello = 1
    </script>
    <template>
      <div class="first">
        <span class="second">{hello}</span>
      </div>
    </template>
    <style lang="postcss">
      .first {
        .second {
          color: red;
        }
      }
    </style>
  `
  const result = await transformSource(source, { url: files.svelte })
  assert.match(result.source, new RegExp(files.svelte))
  assert.match(result.source, /generated by Svelte/)
})

test('transformSource .svelte with warnings ', async () => {
  const source = `
    <script>
      const hello = 1
    </script>
    <span>{hello}</span>
    <style lang="postcss">
      .first { color: red; }
    </style>
  `

  const result = await transformSource(source, { url: files.svelte })
  assert.match(result.source, new RegExp(files.svelte))
  assert.match(result.source, /generated by Svelte/)
})

test.run()
